# Generated by Django 4.1.3 on 2023-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0009_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
