# Generated by Django 4.1.3 on 2024-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0011_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=1024)),
                ('number_of_seats', models.IntegerField(default=1)),
                ('vignette', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=1024, null=True)),
                ('type', models.ManyToManyField(to='yamod.type')),
            ],
        ),
    ]
