# Generated by Django 4.1.3 on 2024-01-24 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yamod', '0014_vehicle_lan_vehicle_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('info', models.CharField(max_length=1024, null=True)),
                ('price', models.CharField(max_length=1024, null=True)),
                ('person_that_books', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ManyToManyField(to='yamod.vehicle')),
            ],
        ),
    ]
